CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username varchar(20) NOT NULL,
	password varchar(200) NOT NULL
);

CREATE TABLE items (
	item_id SERIAL PRIMARY KEY,
	user_id int4 NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	text varchar(2000) NOT NULL,
	privacy varchar(7) NOT NULL,
	midiData varchar(10000)
);


CREATE TABLE recordings (
	recording_id SERIAL PRIMARY KEY,
	user_id int4 NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	name varchar(256) NOT NULL,
	description varchar(2000) NOT NULL,
	privacy varchar(7) NOT NULL,
	audio BYTEA NOT NULL
);

CREATE TABLE instruments (
	instrument_id SERIAL PRIMARY KEY,
	user_id int4 NOT NULL REFERENCES users(id) ON DELETE CASCADE,
	name varchar(256) NOT NULL,
	description varchar(2000) NOT NULL,
	privacy varchar(7) NOT NULL,
	C4 BYTEA NOT NULL,
	Db4 BYTEA NOT NULL,
	D4 BYTEA NOT NULL,
	Eb4 BYTEA NOT NULL,
	E4 BYTEA NOT NULL,
	F4 BYTEA NOT NULL,
	Gb4 BYTEA NOT NULL,
	G4 BYTEA NOT NULL,
	Ab4 BYTEA NOT NULL,
	A4 BYTEA NOT NULL,
	Bb4 BYTEA NOT NULL,
	B4 BYTEA NOT NULL,
	C5 BYTEA NOT NULL,
	Db5 BYTEA NOT NULL,
	D5 BYTEA NOT NULL,
	Eb5 BYTEA NOT NULL,
	E5 BYTEA NOT NULL,
	F5 BYTEA NOT NULL,
	Gb5 BYTEA NOT NULL,
	G5 BYTEA NOT NULL,
	Ab5 BYTEA NOT NULL,
	A5 BYTEA NOT NULL,
	Bb5 BYTEA NOT NULL,
	B5 BYTEA NOT NULL,
	C6 BYTEA NOT NULL
);

